name: tentacula_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - uvicorn==0.41.0 # Веб-сервера ASGI
  - httptools==0.7.1 # C-библиотека для парсинга HTTP (зависимость uvicorn)
  - fastapi[all]==0.134.0 # Веб-фреймворк для создания API
  - starlette==0.52.1 # Фреймворк ASGI для создания асинхронных веб-сервисов на Python
  - python-dotenv==1.2.1 # Чтение переменных окружения и .env
  - apscheduler==3.11.2 # Приложение для шедуллера запускающего события по расписнаию
  - SQLAlchemy==2.0.47 # Работа с БД
  - psycopg2-binary==2.9.10 # Расширения для работы с PostgreSQL
  - asyncpg==0.31.0 # Работа с асинхронностью БД
  - jinja2==3.1.6 # Шаблонизатор для генирациии конфигурационного файла NGINX
  - pydantic==2.12.5 # Проверка входных данных в POST-запросах на инстансы
  - pip-system-certs==5.3 # Разрешает использовать системные SSL-сертификаты
  - httpx==0.28.1 # Клиентская HTTP-библиотека для Python
  - cryptography==46.0.5 # Для работы с криптографией
  - smbprotocol==1.16.0 # Для работы по SMB
  - pip # Для установки зависимостей, которых нет в Conda (python-ldap 3.4.5)
